import { db } from './firebase';
import {
  collection, doc, getDoc, getDocs, setDoc, updateDoc,
  query, where, serverTimestamp, addDoc, Timestamp,
  deleteDoc
} from 'firebase/firestore';
import { AppUser } from './auth';

export interface BreakInterval {
  start: Timestamp;
  end: Timestamp | null;
}

export interface AttendanceRecord {
  id?: string;
  userId: string;
  date: string; // YYYY-MM-DD
  punchIn: Timestamp; // Timestamp
  punchOut: Timestamp | null; // Timestamp
  totalHours: number;
  overtimeHours: number;
  status: 'present' | 'leave' | 'half-day';
  autoGenerated?: boolean; // To identify if it was auto-filled
  workMode?: 'office' | 'remote';
  punchInLocation?: { latitude: number; longitude: number; accuracy?: number } | null;
  punchOutLocation?: { latitude: number; longitude: number; accuracy?: number } | null;
  breaks?: BreakInterval[];
}

// Get current date string in YYYY-MM-DD format
export const getTodayDateString = () => {
  const today = new Date();
  return today.toISOString().split('T')[0];
};

// Check if user has punched in today
export const getTodayAttendance = async (userId: string): Promise<AttendanceRecord | null> => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);
  if (snap.exists()) {
    return { id: snap.id, ...snap.data() } as AttendanceRecord;
  }
  return null;
};

// Punch In
export const punchIn = async (
  userId: string,
  workMode?: 'office' | 'remote',
  location?: { latitude: number; longitude: number; accuracy?: number }
) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);

  const record: AttendanceRecord = {
    userId,
    date: dateStr,
    punchIn: serverTimestamp() as unknown as Timestamp,
    punchOut: null,
    totalHours: 0,
    overtimeHours: 0,
    status: 'present',
    workMode,
    punchInLocation: location || null
  };

  await setDoc(docRef, record);
};

// Helper to calculate total break time in milliseconds
export const getBreakTimeMs = (breaks?: BreakInterval[], upToTime: number = Date.now()): number => {
  if (!breaks || breaks.length === 0) return 0;
  let totalMs = 0;
  for (const b of breaks) {
    if (!b.start) continue;
    const startMs = typeof b.start.toDate === 'function' ? b.start.toDate().getTime() : new Date(b.start as unknown as string).getTime();
    const endMs = b.end 
      ? (typeof b.end.toDate === 'function' ? b.end.toDate().getTime() : new Date(b.end as unknown as string).getTime())
      : upToTime;
    totalMs += Math.max(0, endMs - startMs);
  }
  return totalMs;
};

// Pause Work (Remote worker only)
export const pauseWork = async (userId: string) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);

  if (!snap.exists()) throw new Error("No punch in record found for today.");

  const data = snap.data() as AttendanceRecord;
  if (data.punchOut) throw new Error("Already punched out.");

  const breaks = data.breaks || [];
  
  // Check if already paused
  const hasActiveBreak = breaks.some(b => b.end === null);
  if (hasActiveBreak) throw new Error("Already on break.");

  breaks.push({
    start: Timestamp.now(),
    end: null
  });

  await updateDoc(docRef, { breaks });
};

// Resume Work (Remote worker only)
export const resumeWork = async (userId: string) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);

  if (!snap.exists()) throw new Error("No punch in record found for today.");

  const data = snap.data() as AttendanceRecord;
  if (data.punchOut) throw new Error("Already punched out.");

  const breaks = data.breaks || [];
  
  // Find the active break
  const activeBreakIndex = breaks.findIndex(b => b.end === null);
  if (activeBreakIndex === -1) throw new Error("Not currently on break.");

  breaks[activeBreakIndex].end = Timestamp.now();

  await updateDoc(docRef, { breaks });
};

// Punch Out and Calculate Hours
export const punchOut = async (
  userId: string,
  location?: { latitude: number; longitude: number; accuracy?: number }
) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);

  if (!snap.exists()) throw new Error("No punch in record found for today.");

  const data = snap.data() as AttendanceRecord;
  if (data.punchOut) throw new Error("Already punched out.");

  const punchInTime = (data.punchIn as Timestamp).toDate().getTime();
  const punchOutDate = new Date();
  const punchOutTime = punchOutDate.getTime();

  // Handle active breaks if user punches out while on break
  const breaks = data.breaks || [];
  const hasActiveBreak = breaks.some(b => b.end === null);
  const updatedBreaks = breaks.map(b => {
    if (b.end === null) {
      return { ...b, end: Timestamp.fromDate(punchOutDate) };
    }
    return b;
  });

  // Calculate total break duration
  const totalBreakMs = getBreakTimeMs(updatedBreaks, punchOutTime);

  const totalMs = punchOutTime - punchInTime - totalBreakMs;
  const totalHours = Math.max(0, totalMs / (1000 * 60 * 60));

  // Standard shift is 9 hours
  let overtimeHours = 0;
  if (totalHours > 9) {
    overtimeHours = totalHours - 9;
  }

  // Calculate status based on local punch out hour
  // Shift is 9 AM to 6 PM (18:00)
  // Left before 6 PM and after 1 PM -> half-day
  // Left before 1 PM -> leave
  const punchOutHour = punchOutDate.getHours();
  let status: 'present' | 'leave' | 'half-day' = 'present';

  if (punchOutHour < 18) {
    if (punchOutHour >= 13) {
      status = 'half-day';
    } else {
      status = 'leave';
    }
  }

  await updateDoc(docRef, {
    punchOut: serverTimestamp(),
    totalHours,
    overtimeHours,
    status,
    punchOutLocation: location || null,
    ...(hasActiveBreak ? { breaks: updatedBreaks } : {})
  });
};

// Apply for leave
export const applyForLeave = async (userId: string, date: string) => {
  const docRef = doc(db, 'attendance', `${userId}_${date}`);
  const record = {
    userId,
    date,
    status: 'leave',
    appliedAt: serverTimestamp()
  };
  await setDoc(docRef, record);
};

// Submit a Work Task
export const submitWorkTask = async (userId: string, taskDescription: string) => {
  const colRef = collection(db, 'tasks');
  await addDoc(colRef, {
    userId,
    description: taskDescription,
    createdAt: serverTimestamp(),
    date: getTodayDateString()
  });
};

// Admin: Get all pending users
export const getPendingUsers = async (): Promise<AppUser[]> => {
  const q = query(collection(db, 'users'), where('role', '==', 'pending'));
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AppUser);
};

// Admin: Get all users
export const getAllUsers = async (): Promise<AppUser[]> => {
  const snap = await getDocs(collection(db, 'users'));
  return snap.docs.map(doc => doc.data() as AppUser);
};

// Admin: Update user profile (name and designation)
export const updateUserProfile = async (
  userId: string,
  data: { displayName?: string; designation?: string; workMode?: 'office' | 'remote' }
) => {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, data);
};

// Admin: Approve User
export const approveUser = async (userId: string) => {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, { role: 'worker' });
};

// Admin: Get all workers' attendance
export const getAllAttendance = async (date: string): Promise<AttendanceRecord[]> => {
  const q = query(collection(db, 'attendance'), where('date', '==', date));
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Admin: Get all attendance records in the database
export const getAllAttendanceRecords = async (): Promise<AttendanceRecord[]> => {
  const snap = await getDocs(collection(db, 'attendance'));
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Admin: Get attendance records for a specific month (YYYY-MM)
export const getAttendanceForMonth = async (monthStr: string): Promise<AttendanceRecord[]> => {
  const q = query(
    collection(db, 'attendance'),
    where('date', '>=', `${monthStr}-01`),
    where('date', '<=', `${monthStr}-31`)
  );
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Worker: Get own attendance history
export const getUserAttendanceHistory = async (userId: string): Promise<AttendanceRecord[]> => {
  const q = query(collection(db, 'attendance'), where('userId', '==', userId));
  const snap = await getDocs(q);
  const records = snap.docs.map(doc => doc.data() as AttendanceRecord);
  // Sort in descending order by date in JavaScript to avoid Firestore composite index requirement
  return records.sort((a, b) => b.date.localeCompare(a.date));
};

export interface WorkTask {
  id: string;
  userId: string;
  description: string;
  createdAt: Timestamp;
  date: string;
}

// Worker: Get own tasks
export const getUserTasks = async (userId: string): Promise<WorkTask[]> => {
  const q = query(collection(db, 'tasks'), where('userId', '==', userId));
  const snap = await getDocs(q);
  const tasks = snap.docs.map(doc => {
    const data = doc.data();
    return {
      id: doc.id,
      userId: data.userId,
      description: data.description,
      createdAt: data.createdAt,
      date: data.date
    } as WorkTask;
  });
  // Sort in descending order by createdAt
  return tasks.sort((a, b) => {
    const timeA = a.createdAt?.toMillis ? a.createdAt.toMillis() : 0;
    const timeB = b.createdAt?.toMillis ? b.createdAt.toMillis() : 0;
    return timeB - timeA;
  });
};

// --- HOLIDAY & AUTO-LEAVE SYSTEM ---

export const markHoliday = async (date: string, description: string) => {
  const docRef = doc(db, 'holidays', date);
  await setDoc(docRef, { date, description, createdAt: serverTimestamp() });
};

export const getHolidays = async (): Promise<string[]> => {
  const snap = await getDocs(collection(db, 'holidays'));
  return snap.docs.map(doc => doc.id); // Returns array of date strings 'YYYY-MM-DD'
};

export interface HolidayRecord {
  date: string;
  description: string;
}

export const getHolidayRecords = async (): Promise<HolidayRecord[]> => {
  const snap = await getDocs(collection(db, 'holidays'));
  return snap.docs.map(doc => doc.data() as HolidayRecord);
};

export const deleteHoliday = async (date: string) => {
  const docRef = doc(db, 'holidays', date);
  await deleteDoc(docRef);
};

export const fillMissingLeaves = async (userId: string) => {
  // 1. Fetch user snapshot, attendance history, and holidays in parallel
  const userRef = doc(db, 'users', userId);
  const [userSnap, attendanceHistory, holidays] = await Promise.all([
    getDoc(userRef),
    getUserAttendanceHistory(userId),
    getHolidays()
  ]);

  if (!userSnap.exists()) return;
  const userData = userSnap.data();
  if (!userData.createdAt) return;

  const startDate = userData.createdAt.toDate();
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // 2. Map existing dates and holidays
  const existingDates = new Set(attendanceHistory.map(a => a.date));
  const holidaySet = new Set(holidays);

  // Only check today if it is after 11:00 AM local time
  const now = new Date();
  const isAfter11AM = now.getHours() >= 11;
  const limitDate = new Date(today);
  if (isAfter11AM) {
    limitDate.setDate(limitDate.getDate() + 1); // Extend limit to include today
  }

  // 4. Iterate from start date
  const currentDate = new Date(startDate);
  currentDate.setHours(0, 0, 0, 0);

  const batchPromises = [];

  while (currentDate < limitDate) {
    const dateStr = currentDate.toISOString().split('T')[0];
    const isSunday = currentDate.getDay() === 0;

    // If not a Sunday, not a Holiday, and no attendance record exists, mark as Leave
    if (!isSunday && !holidaySet.has(dateStr) && !existingDates.has(dateStr)) {
      const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
      batchPromises.push(
        setDoc(docRef, {
          userId,
          date: dateStr,
          status: 'leave',
          autoGenerated: true,
          appliedAt: serverTimestamp()
        })
      );
    }
    currentDate.setDate(currentDate.getDate() + 1);
  }

  // Execute all creations
  if (batchPromises.length > 0) {
    await Promise.all(batchPromises);
  }
};

// --- OFFICE LOCATION SETTINGS SYSTEM ---

export interface OfficeSettings {
  latitude: number;
  longitude: number;
  radius: number; // in meters
}

export const getOfficeSettings = async (): Promise<OfficeSettings> => {
  try {
    const docRef = doc(db, 'settings', 'office');
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      return snap.data() as OfficeSettings;
    }
  } catch (error) {
    console.error("Error fetching office settings:", error);
  }
  // Default office location: e.g. Tech Park, Chennai / Bangalore: 12.9716, 77.5946
  return {
    latitude: 12.9716,
    longitude: 77.5946,
    radius: 200 // 200 meters default
  };
};

export const updateOfficeSettings = async (settings: OfficeSettings) => {
  const docRef = doc(db, 'settings', 'office');
  await setDoc(docRef, settings);
};
