import { db } from './firebase';
import {
  collection, doc, getDoc, getDocs, setDoc, updateDoc,
  query, where, serverTimestamp, addDoc, Timestamp,
  deleteDoc
} from 'firebase/firestore';
import { AppUser } from './auth';

export interface BreakInterval {
  start: Timestamp;
  end: Timestamp | null;
}

export interface AttendanceRecord {
  id?: string;
  userId: string;
  date: string; // YYYY-MM-DD
  punchIn: Timestamp; // Timestamp
  punchOut: Timestamp | null; // Timestamp
  totalHours: number;
  overtimeHours: number;
  status: 'present' | 'leave' | 'half-day';
  autoGenerated?: boolean; // To identify if it was auto-filled
  workMode?: 'office' | 'remote';
  punchInLocation?: { latitude: number; longitude: number; accuracy?: number } | null;
  punchOutLocation?: { latitude: number; longitude: number; accuracy?: number } | null;
  breaks?: BreakInterval[];
}

// Helper to format Date object into YYYY-MM-DD in local timezone
export const formatLocalDate = (d: Date): string => {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

// Get current date string in YYYY-MM-DD format
export const getTodayDateString = () => {
  return formatLocalDate(new Date());
};

// Check if user has punched in today
export const getTodayAttendance = async (userId: string): Promise<AttendanceRecord | null> => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);
  if (snap.exists()) {
    return { id: snap.id, ...snap.data() } as AttendanceRecord;
  }
  return null;
};

// Punch In
export const punchIn = async (
  userId: string,
  workMode?: 'office' | 'remote',
  location?: { latitude: number; longitude: number; accuracy?: number }
) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);

  const record: AttendanceRecord = {
    userId,
    date: dateStr,
    punchIn: serverTimestamp() as unknown as Timestamp,
    punchOut: null,
    totalHours: 0,
    overtimeHours: 0,
    status: 'present',
    workMode,
    punchInLocation: location || null
  };

  await setDoc(docRef, record);
};

// Helper to calculate total break time in milliseconds
export const getBreakTimeMs = (breaks?: BreakInterval[], upToTime: number = Date.now()): number => {
  if (!breaks || breaks.length === 0) return 0;
  let totalMs = 0;
  for (const b of breaks) {
    if (!b.start) continue;
    const startMs = typeof b.start.toDate === 'function' ? b.start.toDate().getTime() : new Date(b.start as unknown as string).getTime();
    const endMs = b.end
      ? (typeof b.end.toDate === 'function' ? b.end.toDate().getTime() : new Date(b.end as unknown as string).getTime())
      : upToTime;
    totalMs += Math.max(0, endMs - startMs);
  }
  return totalMs;
};

// Pause Work (Remote worker only)
export const pauseWork = async (userId: string) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);

  if (!snap.exists()) throw new Error("No punch in record found for today.");

  const data = snap.data() as AttendanceRecord;
  if (data.punchOut) throw new Error("Already punched out.");

  const breaks = data.breaks || [];

  // Check if already paused
  const hasActiveBreak = breaks.some(b => b.end === null);
  if (hasActiveBreak) throw new Error("Already on break.");

  breaks.push({
    start: Timestamp.now(),
    end: null
  });

  await updateDoc(docRef, { breaks });
};

// Resume Work (Remote worker only)
export const resumeWork = async (userId: string) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);

  if (!snap.exists()) throw new Error("No punch in record found for today.");

  const data = snap.data() as AttendanceRecord;
  if (data.punchOut) throw new Error("Already punched out.");

  const breaks = data.breaks || [];

  // Find the active break
  const activeBreakIndex = breaks.findIndex(b => b.end === null);
  if (activeBreakIndex === -1) throw new Error("Not currently on break.");

  breaks[activeBreakIndex].end = Timestamp.now();

  await updateDoc(docRef, { breaks });
};

// Punch Out and Calculate Hours
export const punchOut = async (
  userId: string,
  location?: { latitude: number; longitude: number; accuracy?: number }
) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);

  if (!snap.exists()) throw new Error("No punch in record found for today.");

  const data = snap.data() as AttendanceRecord;
  if (data.punchOut) throw new Error("Already punched out.");

  const punchInTime = (data.punchIn as Timestamp).toDate().getTime();
  const punchOutDate = new Date();
  const punchOutTime = punchOutDate.getTime();

  // Handle active breaks if user punches out while on break
  const breaks = data.breaks || [];
  const hasActiveBreak = breaks.some(b => b.end === null);
  const updatedBreaks = breaks.map(b => {
    if (b.end === null) {
      return { ...b, end: Timestamp.fromDate(punchOutDate) };
    }
    return b;
  });

  // Calculate total break duration
  const totalBreakMs = getBreakTimeMs(updatedBreaks, punchOutTime);

  const totalMs = punchOutTime - punchInTime - totalBreakMs;
  const totalHours = Math.max(0, totalMs / (1000 * 60 * 60));

  // Standard shift is 9 hours
  let overtimeHours = 0;
  if (totalHours > 9) {
    overtimeHours = totalHours - 9;
  }

  // Calculate status based on local punch out hour
  // Shift is 9 AM to 6 PM (18:00)
  // Left before 6 PM and after 1 PM -> half-day
  // Left before 1 PM -> leave
  const punchOutHour = punchOutDate.getHours();
  let status: 'present' | 'leave' | 'half-day' = 'present';

  if (punchOutHour < 18) {
    if (punchOutHour >= 13) {
      status = 'half-day';
    } else {
      status = 'leave';
    }
  }

  await updateDoc(docRef, {
    punchOut: serverTimestamp(),
    totalHours,
    overtimeHours,
    status,
    punchOutLocation: location || null,
    ...(hasActiveBreak ? { breaks: updatedBreaks } : {})
  });
};

// Apply for leave
export const applyForLeave = async (userId: string, date: string) => {
  const docRef = doc(db, 'attendance', `${userId}_${date}`);
  const record = {
    userId,
    date,
    status: 'leave',
    appliedAt: serverTimestamp()
  };
  await setDoc(docRef, record);
};

// Submit a Work Task
export const submitWorkTask = async (userId: string, taskDescription: string) => {
  const colRef = collection(db, 'tasks');
  await addDoc(colRef, {
    userId,
    description: taskDescription,
    createdAt: serverTimestamp(),
    date: getTodayDateString()
  });
};

// Admin: Get all pending users
export const getPendingUsers = async (): Promise<AppUser[]> => {
  const q = query(collection(db, 'users'), where('role', '==', 'pending'));
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AppUser);
};

// Admin: Get all users
export const getAllUsers = async (): Promise<AppUser[]> => {
  const snap = await getDocs(collection(db, 'users'));
  return snap.docs.map(doc => doc.data() as AppUser);
};

// Admin: Update user profile (name and designation)
export const updateUserProfile = async (
  userId: string,
  data: { displayName?: string; designation?: string; workMode?: 'office' | 'remote' }
) => {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, data);
};

// Worker: Update own salary start day
export const updateSalaryStartDay = async (userId: string, startDay: number) => {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, { salaryStartDay: startDay });
};

// Admin: Approve User
export const approveUser = async (userId: string) => {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, { role: 'worker' });
};

// Admin: Get all workers' attendance
export const getAllAttendance = async (date: string): Promise<AttendanceRecord[]> => {
  const q = query(collection(db, 'attendance'), where('date', '==', date));
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Admin: Get all attendance records in the database
export const getAllAttendanceRecords = async (): Promise<AttendanceRecord[]> => {
  const snap = await getDocs(collection(db, 'attendance'));
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Admin: Get attendance records for a specific month (YYYY-MM)
export const getAttendanceForMonth = async (monthStr: string): Promise<AttendanceRecord[]> => {
  const q = query(
    collection(db, 'attendance'),
    where('date', '>=', `${monthStr}-01`),
    where('date', '<=', `${monthStr}-31`)
  );
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Get attendance records covering custom salary period boundaries (prev, curr, next months)
export const getAttendanceForSalaryRange = async (monthStr: string): Promise<AttendanceRecord[]> => {
  const [year, month] = monthStr.split('-').map(Number);

  const prevMonthYear = month === 1 ? year - 1 : year;
  const prevMonth = month === 1 ? 12 : month - 1;
  const prevMonthStr = `${prevMonthYear}-${String(prevMonth).padStart(2, '0')}`;

  const nextMonthYear = month === 12 ? year + 1 : year;
  const nextMonth = month === 12 ? 1 : month + 1;
  const nextMonthStr = `${nextMonthYear}-${String(nextMonth).padStart(2, '0')}`;

  const [prevDocs, currDocs, nextDocs] = await Promise.all([
    getAttendanceForMonth(prevMonthStr),
    getAttendanceForMonth(monthStr),
    getAttendanceForMonth(nextMonthStr)
  ]);

  const map = new Map<string, AttendanceRecord>();
  prevDocs.forEach(d => map.set(d.id || `${d.userId}_${d.date}`, d));
  currDocs.forEach(d => map.set(d.id || `${d.userId}_${d.date}`, d));
  nextDocs.forEach(d => map.set(d.id || `${d.userId}_${d.date}`, d));
  return Array.from(map.values());
};

// Admin: Get attendance records in a date range (YYYY-MM-DD to YYYY-MM-DD)
export const getAttendanceForDateRange = async (startDate: string, endDate: string): Promise<AttendanceRecord[]> => {
  const q = query(
    collection(db, 'attendance'),
    where('date', '>=', startDate),
    where('date', '<=', endDate)
  );
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Calculate starting and ending date of active salary cycle for a given start day
export const getCurrentSalaryPeriod = (startDay: number, refDate: Date = new Date()) => {
  const year = refDate.getFullYear();
  const month = refDate.getMonth();
  const day = refDate.getDate();

  let startYear = year;
  let startMonth = month;

  if (day < startDay) {
    startMonth = month === 0 ? 11 : month - 1;
    startYear = month === 0 ? year - 1 : year;
  }

  const startDate = new Date(startYear, startMonth, startDay);
  const endDate = new Date(startYear, startMonth + 1, startDay);

  const formatYYYYMMDD = (d: Date) => {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const dayStr = String(d.getDate()).padStart(2, '0');
    return `${y}-${m}-${dayStr}`;
  };

  return {
    startDate: formatYYYYMMDD(startDate),
    endDate: formatYYYYMMDD(endDate)
  };
};


// Worker: Get own attendance history
export const getUserAttendanceHistory = async (userId: string): Promise<AttendanceRecord[]> => {
  const q = query(collection(db, 'attendance'), where('userId', '==', userId));
  const snap = await getDocs(q);
  const records = snap.docs.map(doc => doc.data() as AttendanceRecord);
  // Sort in descending order by date in JavaScript to avoid Firestore composite index requirement
  return records.sort((a, b) => b.date.localeCompare(a.date));
};

export interface WorkTask {
  id: string;
  userId: string;
  description: string;
  createdAt: Timestamp;
  date: string;
}

// Worker: Get own tasks
export const getUserTasks = async (userId: string): Promise<WorkTask[]> => {
  const q = query(collection(db, 'tasks'), where('userId', '==', userId));
  const snap = await getDocs(q);
  const tasks = snap.docs.map(doc => {
    const data = doc.data();
    return {
      id: doc.id,
      userId: data.userId,
      description: data.description,
      createdAt: data.createdAt,
      date: data.date
    } as WorkTask;
  });
  // Sort in descending order by createdAt
  return tasks.sort((a, b) => {
    const timeA = a.createdAt?.toMillis ? a.createdAt.toMillis() : 0;
    const timeB = b.createdAt?.toMillis ? b.createdAt.toMillis() : 0;
    return timeB - timeA;
  });
};

// --- HOLIDAY & AUTO-LEAVE SYSTEM ---

export const markHoliday = async (date: string, description: string) => {
  const docRef = doc(db, 'holidays', date);
  await setDoc(docRef, { date, description, createdAt: serverTimestamp() });
};

export const getHolidays = async (): Promise<string[]> => {
  const snap = await getDocs(collection(db, 'holidays'));
  return snap.docs.map(doc => doc.id); // Returns array of date strings 'YYYY-MM-DD'
};

export interface HolidayRecord {
  date: string;
  description: string;
}

export const getHolidayRecords = async (): Promise<HolidayRecord[]> => {
  const snap = await getDocs(collection(db, 'holidays'));
  return snap.docs.map(doc => doc.data() as HolidayRecord);
};

export const deleteHoliday = async (date: string) => {
  const docRef = doc(db, 'holidays', date);
  await deleteDoc(docRef);
};

export const fillMissingLeaves = async (userId: string) => {
  // 1. Fetch user snapshot, attendance history, and holidays in parallel
  const userRef = doc(db, 'users', userId);
  const [userSnap, attendanceHistory, holidays] = await Promise.all([
    getDoc(userRef),
    getUserAttendanceHistory(userId),
    getHolidays()
  ]);

  if (!userSnap.exists()) return;
  const userData = userSnap.data();
  if (!userData.createdAt) return;

  const startDate = userData.createdAt.toDate();
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // 2. Map existing dates and holidays
  const existingDates = new Set(attendanceHistory.map(a => a.date));
  const holidaySet = new Set(holidays);

  // Only check today if it is after 11:00 AM local time
  const now = new Date();
  const isAfter11AM = now.getHours() >= 11;
  const limitDate = new Date(today);
  if (isAfter11AM) {
    limitDate.setDate(limitDate.getDate() + 1); // Extend limit to include today
  }

  // 4. Iterate from start date
  const currentDate = new Date(startDate);
  currentDate.setHours(0, 0, 0, 0);

  const batchPromises = [];

  while (currentDate < limitDate) {
    const dateStr = formatLocalDate(currentDate);
    const isSunday = currentDate.getDay() === 0;

    // If not a Sunday, not a Holiday, and no attendance record exists, mark as Leave
    if (!isSunday && !holidaySet.has(dateStr) && !existingDates.has(dateStr)) {
      const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
      batchPromises.push(
        setDoc(docRef, {
          userId,
          date: dateStr,
          status: 'leave',
          autoGenerated: true,
          appliedAt: serverTimestamp()
        })
      );
    }
    currentDate.setDate(currentDate.getDate() + 1);
  }

  // Execute all creations
  if (batchPromises.length > 0) {
    await Promise.all(batchPromises);
  }
};

// --- OFFICE LOCATION SETTINGS SYSTEM ---

export interface OfficeSettings {
  latitude: number;
  longitude: number;
  radius: number; // in meters
}

export const getOfficeSettings = async (): Promise<OfficeSettings> => {
  try {
    const docRef = doc(db, 'settings', 'office');
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      return snap.data() as OfficeSettings;
    }
  } catch (error) {
    console.error("Error fetching office settings:", error);
  }
  // Default office location: e.g. Tech Park, Chennai / Bangalore: 12.9716, 77.5946
  return {
    latitude: 12.9716,
    longitude: 77.5946,
    radius: 200 // 200 meters default
  };
};

export const updateOfficeSettings = async (settings: OfficeSettings) => {
  const docRef = doc(db, 'settings', 'office');
  await setDoc(docRef, settings);
};

// --- USER SUGGESTIONS & BUG REPORTING SYSTEM ---

export interface UserFeedback {
  id: string;
  userId: string;
  userName: string;
  userEmail: string;
  userPhoto?: string;
  type: 'suggestion' | 'bug';
  title: string;
  description: string;
  status: 'pending' | 'in-progress' | 'completed' | 'declined';
  upvotes: string[];
  createdAt: Timestamp;
}

export const submitFeedback = async (
  userId: string,
  userName: string,
  userEmail: string,
  userPhoto: string,
  type: 'suggestion' | 'bug',
  title: string,
  description: string
) => {
  const colRef = collection(db, 'feedback');
  await addDoc(colRef, {
    userId,
    userName,
    userEmail,
    userPhoto: userPhoto || '',
    type,
    title,
    description,
    status: 'pending',
    upvotes: [],
    createdAt: serverTimestamp()
  });
};

export const getAllFeedback = async (): Promise<UserFeedback[]> => {
  const snap = await getDocs(collection(db, 'feedback'));
  const items = snap.docs.map(doc => {
    const data = doc.data();
    return {
      id: doc.id,
      userId: data.userId,
      userName: data.userName,
      userEmail: data.userEmail,
      userPhoto: data.userPhoto,
      type: data.type,
      title: data.title,
      description: data.description,
      status: data.status || 'pending',
      upvotes: data.upvotes || [],
      createdAt: data.createdAt
    } as UserFeedback;
  });
  // Sort in descending order by createdAt
  return items.sort((a, b) => {
    const timeA = a.createdAt?.toMillis ? a.createdAt.toMillis() : 0;
    const timeB = b.createdAt?.toMillis ? b.createdAt.toMillis() : 0;
    return timeB - timeA;
  });
};

export const toggleUpvoteFeedback = async (feedbackId: string, userId: string) => {
  const docRef = doc(db, 'feedback', feedbackId);
  const snap = await getDoc(docRef);
  if (!snap.exists()) throw new Error("Feedback record not found.");
  const data = snap.data();
  const upvotes: string[] = data.upvotes || [];
  const index = upvotes.indexOf(userId);
  if (index === -1) {
    upvotes.push(userId);
  } else {
    upvotes.splice(index, 1);
  }
  await updateDoc(docRef, { upvotes });
};

export const updateFeedbackStatus = async (
  feedbackId: string,
  status: 'pending' | 'in-progress' | 'completed' | 'declined'
) => {
  const docRef = doc(db, 'feedback', feedbackId);
  await updateDoc(docRef, { status });
};

export const deleteFeedback = async (feedbackId: string) => {
  const docRef = doc(db, 'feedback', feedbackId);
  await deleteDoc(docRef);
};

// --- DYNAMIC SYSTEM CHANGELOG TIMELINE SYSTEM ---

export interface ChangelogRecord {
  id: string;
  version: string;
  date: string;
  title: string;
  badge: string;
  badgeColor: string;
  items: string[];
  createdAt: Timestamp;
}

const DEFAULT_CHANGELOGS = [
  {
    version: "v1.8",
    date: "June 2, 2026",
    title: "Custom 404 Page & Pre-compiled Git Logs",
    badge: "Current Update",
    badgeColor: "var(--primary)",
    items: [
      "Designed a custom 404 Error page themed around screen-printing and apparel graphics.",
      "Rendered an animated SVG shirt with multi-layer off-registration effects and alarm indicators.",
      "Implemented a pre-build caching script compiling GitHub commit logs into the static bundle for production deployments."
    ]
  },
  {
    version: "v1.7",
    date: "June 2, 2026",
    title: "Responsive Alignment & Button Layouts",
    badge: "Feature Release",
    badgeColor: "var(--accent)",
    items: [
      "Corrected button sizes on mobile screens, restoring standard action buttons to normal size.",
      "Introduced compact, inline filter buttons on mobile to fit the viewport width cleanly.",
      "Adjusted form layouts to stack vertically and statically on mobile while remaining sticky on desktop."
    ]
  },
  {
    version: "v1.6",
    date: "June 2, 2026",
    title: "Developer Updates & Feedback Board",
    badge: "Feature Release",
    badgeColor: "var(--accent)",
    items: [
      "Added the Developer Page accessible via the navigation bar.",
      "Integrated a static project evolution timeline from v1.0 onwards.",
      "Built a suggestions board for feature proposals ('what to add next').",
      "Created a bug reporting portal with interactive ticket creation.",
      "Added real-time status management (Pending, In Progress, Completed, Declined) for administrators.",
      "Implemented a user-driven upvote system for feedback prioritization."
    ]
  },
  {
    version: "v1.5",
    date: "May 25, 2026",
    title: "Overtime Calculator Tool",
    badge: "Feature Release",
    badgeColor: "var(--accent)",
    items: [
      "Created a dedicated client-side overtime calculation calculator tool.",
      "Added manual sliders and fields to adjust hourly rates and verify projected income.",
      "Designed a responsive matrix showing earnings based on standard and weekend multiplier variables."
    ]
  },
  {
    version: "v1.4",
    date: "May 10, 2026",
    title: "Holiday System & Auto-Leave Filler",
    badge: "Automation",
    badgeColor: "var(--success)",
    items: [
      "Integrated a public holiday management catalog inside the admin panel.",
      "Designed an automatic leaves generator filling unlogged week days as 'leave' to keep accurate timesheets.",
      "Added exceptions to avoid auto-filling leaves on Sundays and customized company holidays."
    ]
  },
  {
    version: "v1.3",
    date: "April 28, 2026",
    title: "Admin Panel & Security Upgrades",
    badge: "Administration",
    badgeColor: "var(--secondary)",
    items: [
      "Built a full administrative module to manage users and access levels.",
      "Created a worker verification approval queue to audit new user logins.",
      "Configured custom office geographic boundaries and coordinate radii for location-locked check-ins."
    ]
  },
  {
    version: "v1.2",
    date: "April 15, 2026",
    title: "Geolocation Geofencing Integration",
    badge: "Security",
    badgeColor: "var(--warning)",
    items: [
      "Implemented HTML5 Geolocation tracking on punch-in and punch-out events.",
      "Added a check calculating distance to the physical Chennai/Bangalore printing facility.",
      "Restricted office-mode check-ins to a 200-meter threshold with live distance indicators."
    ]
  },
  {
    version: "v1.1",
    date: "March 30, 2026",
    title: "Breaks & remote Work Logs",
    badge: "Optimization",
    badgeColor: "#8b5cf6",
    items: [
      "Designed pause and resume functionality to track break times.",
      "Added work mode tags allowing selection of office or remote checks.",
      "Updated shift calculators to automatically subtract aggregate break time from payroll hours."
    ]
  },
  {
    version: "v1.0",
    date: "March 15, 2026",
    title: "First Release",
    badge: "Launch",
    badgeColor: "#6b7280",
    items: [
      "Launched Google Workspace Auth integration restricting sign-in to verified members.",
      "Configured standard 9-hour work day timers and overtime thresholds.",
      "Created personal history tables listing punch cards and daily task submission summaries."
    ]
  }
];

const mapChangelogSnap = (snap: any): ChangelogRecord[] => {
  const records = snap.docs.map((doc: any) => {
    const data = doc.data();
    return {
      id: doc.id,
      version: data.version,
      date: data.date,
      title: data.title,
      badge: data.badge,
      badgeColor: data.badgeColor,
      items: data.items || [],
      createdAt: data.createdAt
    } as ChangelogRecord;
  });

  // Sort in descending order by createdAt
  return records.sort((a: ChangelogRecord, b: ChangelogRecord) => {
    const timeA = a.createdAt?.toMillis ? a.createdAt.toMillis() : 0;
    const timeB = b.createdAt?.toMillis ? b.createdAt.toMillis() : 0;
    return timeB - timeA;
  });
};

export const getChangelogs = async (): Promise<ChangelogRecord[]> => {
  const colRef = collection(db, 'changelogs');
  const snap = await getDocs(colRef);

  const existingDocs = snap.docs.map(doc => doc.data() as ChangelogRecord);
  const existingVersions = new Set(existingDocs.map(d => d.version));

  const missingLogs = DEFAULT_CHANGELOGS.filter(item => !existingVersions.has(item.version));

  if (missingLogs.length > 0) {
    // Seed Firestore with missing default release logs
    const seedPromises = missingLogs.map((item, index) => {
      // Offset base time so sorting stays chronological
      const baseTime = Date.now() - (index * 60 * 1000);
      return addDoc(colRef, {
        ...item,
        createdAt: Timestamp.fromMillis(baseTime)
      });
    });
    await Promise.all(seedPromises);

    // Re-fetch updated data
    const newSnap = await getDocs(colRef);
    return mapChangelogSnap(newSnap);
  }

  return mapChangelogSnap(snap);
};

export const createChangelog = async (
  version: string,
  date: string,
  title: string,
  badge: string,
  badgeColor: string,
  items: string[]
) => {
  const colRef = collection(db, 'changelogs');
  await addDoc(colRef, {
    version,
    date,
    title,
    badge,
    badgeColor,
    items,
    createdAt: serverTimestamp()
  });
};

export const deleteChangelog = async (id: string) => {
  const docRef = doc(db, 'changelogs', id);
  await deleteDoc(docRef);
};


