import { db } from './firebase';
import { 
  collection, doc, getDoc, getDocs, setDoc, updateDoc, 
  query, where, orderBy, serverTimestamp, addDoc, Timestamp 
} from 'firebase/firestore';
import { AppUser } from './auth';

export interface AttendanceRecord {
  id?: string;
  userId: string;
  date: string; // YYYY-MM-DD
  punchIn: any; // Timestamp
  punchOut: any | null; // Timestamp
  totalHours: number;
  overtimeHours: number;
  status: 'present' | 'leave' | 'half-day';
  autoGenerated?: boolean; // To identify if it was auto-filled
}

// Get current date string in YYYY-MM-DD format
export const getTodayDateString = () => {
  const today = new Date();
  return today.toISOString().split('T')[0];
};

// Check if user has punched in today
export const getTodayAttendance = async (userId: string): Promise<AttendanceRecord | null> => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);
  if (snap.exists()) {
    return { id: snap.id, ...snap.data() } as AttendanceRecord;
  }
  return null;
};

// Punch In
export const punchIn = async (userId: string) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  
  const record: AttendanceRecord = {
    userId,
    date: dateStr,
    punchIn: serverTimestamp(),
    punchOut: null,
    totalHours: 0,
    overtimeHours: 0,
    status: 'present'
  };

  await setDoc(docRef, record);
};

// Punch Out and Calculate Hours
export const punchOut = async (userId: string) => {
  const dateStr = getTodayDateString();
  const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
  const snap = await getDoc(docRef);
  
  if (!snap.exists()) throw new Error("No punch in record found for today.");
  
  const data = snap.data() as AttendanceRecord;
  if (data.punchOut) throw new Error("Already punched out.");

  const punchInTime = (data.punchIn as Timestamp).toDate().getTime();
  const punchOutDate = new Date();
  const punchOutTime = punchOutDate.getTime();
  
  const totalMs = punchOutTime - punchInTime;
  const totalHours = totalMs / (1000 * 60 * 60);
  
  // Standard shift is 9 hours
  let overtimeHours = 0;
  if (totalHours > 9) {
    overtimeHours = totalHours - 9;
  }

  // Calculate status based on local punch out hour
  // Shift is 9 AM to 6 PM (18:00)
  // Left before 6 PM and after 1 PM -> half-day
  // Left before 1 PM -> leave
  const punchOutHour = punchOutDate.getHours();
  let status: 'present' | 'leave' | 'half-day' = 'present';

  if (punchOutHour < 18) {
    if (punchOutHour >= 13) {
      status = 'half-day';
    } else {
      status = 'leave';
    }
  }

  await updateDoc(docRef, {
    punchOut: serverTimestamp(),
    totalHours,
    overtimeHours,
    status
  });
};

// Apply for leave
export const applyForLeave = async (userId: string, date: string) => {
  const docRef = doc(db, 'attendance', `${userId}_${date}`);
  const record = {
    userId,
    date,
    status: 'leave',
    appliedAt: serverTimestamp()
  };
  await setDoc(docRef, record);
};

// Submit a Work Task
export const submitWorkTask = async (userId: string, taskDescription: string) => {
  const colRef = collection(db, 'tasks');
  await addDoc(colRef, {
    userId,
    description: taskDescription,
    createdAt: serverTimestamp(),
    date: getTodayDateString()
  });
};

// Admin: Get all pending users
export const getPendingUsers = async (): Promise<AppUser[]> => {
  const q = query(collection(db, 'users'), where('role', '==', 'pending'));
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AppUser);
};

// Admin: Get all users
export const getAllUsers = async (): Promise<AppUser[]> => {
  const snap = await getDocs(collection(db, 'users'));
  return snap.docs.map(doc => doc.data() as AppUser);
};

// Admin: Update user profile (name and designation)
export const updateUserProfile = async (userId: string, data: { displayName?: string, designation?: string }) => {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, data);
};

// Admin: Approve User
export const approveUser = async (userId: string) => {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, { role: 'worker' });
};

// Admin: Get all workers' attendance
export const getAllAttendance = async (date: string): Promise<AttendanceRecord[]> => {
  const q = query(collection(db, 'attendance'), where('date', '==', date));
  const snap = await getDocs(q);
  return snap.docs.map(doc => doc.data() as AttendanceRecord);
};

// Worker: Get own attendance history
export const getUserAttendanceHistory = async (userId: string): Promise<AttendanceRecord[]> => {
  const q = query(collection(db, 'attendance'), where('userId', '==', userId));
  const snap = await getDocs(q);
  const records = snap.docs.map(doc => doc.data() as AttendanceRecord);
  // Sort in descending order by date in JavaScript to avoid Firestore composite index requirement
  return records.sort((a, b) => b.date.localeCompare(a.date));
};

// Worker: Get own tasks
export const getUserTasks = async (userId: string) => {
  const q = query(collection(db, 'tasks'), where('userId', '==', userId));
  const snap = await getDocs(q);
  const tasks = snap.docs.map(doc => ({ id: doc.id, ...doc.data() as any }));
  // Sort in descending order by createdAt
  return tasks.sort((a, b) => {
    const timeA = a.createdAt?.toMillis ? a.createdAt.toMillis() : 0;
    const timeB = b.createdAt?.toMillis ? b.createdAt.toMillis() : 0;
    return timeB - timeA;
  });
};

// --- HOLIDAY & AUTO-LEAVE SYSTEM ---

export const markHoliday = async (date: string, description: string) => {
  const docRef = doc(db, 'holidays', date);
  await setDoc(docRef, { date, description, createdAt: serverTimestamp() });
};

export const getHolidays = async (): Promise<string[]> => {
  const snap = await getDocs(collection(db, 'holidays'));
  return snap.docs.map(doc => doc.id); // Returns array of date strings 'YYYY-MM-DD'
};

export const fillMissingLeaves = async (userId: string) => {
  // 1. Get user to find their start date
  const userRef = doc(db, 'users', userId);
  const userSnap = await getDoc(userRef);
  if (!userSnap.exists()) return;
  const userData = userSnap.data();
  if (!userData.createdAt) return;

  const startDate = userData.createdAt.toDate();
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // 2. Get all existing attendances for user
  const attendanceHistory = await getUserAttendanceHistory(userId);
  const existingDates = new Set(attendanceHistory.map(a => a.date));

  // 3. Get all holidays
  const holidays = await getHolidays();
  const holidaySet = new Set(holidays);

  // 4. Iterate from start date to yesterday
  let currentDate = new Date(startDate);
  currentDate.setHours(0, 0, 0, 0);

  const batchPromises = [];

  while (currentDate < today) {
    const dateStr = currentDate.toISOString().split('T')[0];
    const isSunday = currentDate.getDay() === 0;

    // If not a Sunday, not a Holiday, and no attendance record exists, mark as Leave
    if (!isSunday && !holidaySet.has(dateStr) && !existingDates.has(dateStr)) {
      const docRef = doc(db, 'attendance', `${userId}_${dateStr}`);
      batchPromises.push(
        setDoc(docRef, {
          userId,
          date: dateStr,
          status: 'leave',
          autoGenerated: true,
          appliedAt: serverTimestamp()
        })
      );
    }
    currentDate.setDate(currentDate.getDate() + 1);
  }

  // Execute all creations
  if (batchPromises.length > 0) {
    await Promise.all(batchPromises);
  }
};
